module Maps.Testtown where


import         Data.Array
import         Types.GameMap
import         Types.Tile


map :: GameMap
map =
  GameMap { tiles =
    array ((0,0),(25,20))
    [((0, 0), Tile Grass Nothing [])
    , ((1, 0), Tile Grass Nothing [])
    , ((2, 0), Tile Grass Nothing [])
    , ((3, 0), Tile Grass Nothing [])
    , ((4, 0), Tile Grass Nothing [])
    , ((5, 0), Tile Grass Nothing [])
    , ((6, 0), Tile Grass Nothing [])
    , ((7, 0), Tile Grass Nothing [])
    , ((8, 0), Tile Grass Nothing [])
    , ((9, 0), Tile Grass Nothing [])
    , ((10, 0), Tile Grass Nothing [])
    , ((11, 0), Tile Grass Nothing [])
    , ((12, 0), Tile Grass Nothing [])
    , ((13, 0), Tile Grass Nothing [])
    , ((14, 0), Tile Grass Nothing [])
    , ((15, 0), Tile Grass Nothing [])
    , ((16, 0), Tile Grass Nothing [])
    , ((17, 0), Tile Grass Nothing [])
    , ((18, 0), Tile Grass Nothing [])
    , ((19, 0), Tile Grass Nothing [])
    , ((20, 0), Tile Grass Nothing [])
    , ((21, 0), Tile Grass Nothing [])
    , ((22, 0), Tile Grass Nothing [])
    , ((23, 0), Tile Grass Nothing [])
    , ((24, 0), Tile Grass Nothing [])
    , ((25, 0), Tile Grass Nothing [])
    , ((0, 1), Tile Grass Nothing [])
    , ((1, 1), Tile Snow Nothing [Walk, Fly])
    , ((2, 1), Tile Snow Nothing [Walk, Fly])
    , ((3, 1), Tile Snow Nothing [Walk, Fly])
    , ((4, 1), Tile Grass Nothing [Walk, Fly])
    , ((5, 1), Tile Grass Nothing [Walk, Fly])
    , ((6, 1), Tile Grass Nothing [Walk, Fly])
    , ((7, 1), Tile Grass Nothing [Walk, Fly])
    , ((8, 1), Tile Grass Nothing [Walk, Fly])
    , ((9, 1), Tile Grass Nothing [Walk, Fly])
    , ((10, 1), Tile Grass Nothing [Walk, Fly])
    , ((11, 1), Tile Grass Nothing [Walk, Fly])
    , ((12, 1), Tile Grass Nothing [Walk, Fly])
    , ((13, 1), Tile Grass Nothing [Walk, Fly])
    , ((14, 1), Tile Grass Nothing [Walk, Fly])
    , ((15, 1), Tile Grass Nothing [Walk, Fly])
    , ((16, 1), Tile Grass Nothing [Walk, Fly])
    , ((17, 1), Tile Grass Nothing [Walk, Fly])
    , ((18, 1), Tile Grass Nothing [Walk, Fly])
    , ((19, 1), Tile Grass Nothing [Walk, Fly])
    , ((20, 1), Tile Grass Nothing [Walk, Fly])
    , ((21, 1), Tile Grass Nothing [Walk, Fly])
    , ((22, 1), Tile Grass Nothing [Walk, Fly])
    , ((23, 1), Tile Grass Nothing [Walk, Fly])
    , ((24, 1), Tile Grass Nothing [Walk, Fly])
    , ((25, 1), Tile Grass Nothing [])
    , ((0, 2), Tile Grass Nothing [])
    , ((1, 2), Tile Snow Nothing [Walk, Fly])
    , ((2, 2), Tile Snow Nothing [Walk, Fly])
    , ((3, 2), Tile Grass Nothing [Walk, Fly])
    , ((4, 2), Tile Grass Nothing [Walk, Fly])
    , ((5, 2), Tile Grass Nothing [Walk, Fly])
    , ((6, 2), Tile Grass Nothing [Walk, Fly])
    , ((7, 2), Tile Grass Nothing [Walk, Fly])
    , ((8, 2), Tile Grass Nothing [Walk, Fly])
    , ((9, 2), Tile Grass Nothing [Walk, Fly])
    , ((10, 2), Tile Grass Nothing [Walk, Fly])
    , ((11, 2), Tile Grass Nothing [Walk, Fly])
    , ((12, 2), Tile Grass Nothing [Walk, Fly])
    , ((13, 2), Tile Grass Nothing [Walk, Fly])
    , ((14, 2), Tile Grass Nothing [Walk, Fly])
    , ((15, 2), Tile Grass Nothing [Walk, Fly])
    , ((16, 2), Tile Grass Nothing [Walk, Fly])
    , ((17, 2), Tile Grass Nothing [Walk, Fly])
    , ((18, 2), Tile Grass Nothing [Walk, Fly])
    , ((19, 2), Tile Water Nothing [Fly, Swim])
    , ((20, 2), Tile Grass Nothing [Walk, Fly])
    , ((21, 2), Tile Grass Nothing [Walk, Fly])
    , ((22, 2), Tile Grass Nothing [Walk, Fly])
    , ((23, 2), Tile Grass Nothing [Walk, Fly])
    , ((24, 2), Tile Grass Nothing [Walk, Fly])
    , ((25, 2), Tile Grass Nothing [])
    , ((0, 3), Tile Grass Nothing [])
    , ((1, 3), Tile Snow Nothing [Walk, Fly])
    , ((2, 3), Tile Grass Nothing [Walk, Fly])
    , ((3, 3), Tile Grass Nothing [Walk, Fly])
    , ((4, 3), Tile Grass Nothing [Walk, Fly])
    , ((5, 3), Tile Grass Nothing [Walk, Fly])
    , ((6, 3), Tile Grass Nothing [Walk, Fly])
    , ((7, 3), Tile Grass Nothing [Walk, Fly])
    , ((8, 3), Tile Grass Nothing [Walk, Fly])
    , ((9, 3), Tile Grass Nothing [Walk, Fly])
    , ((10, 3), Tile Grass Nothing [Walk, Fly])
    , ((11, 3), Tile Grass Nothing [Walk, Fly])
    , ((12, 3), Tile Grass Nothing [Walk, Fly])
    , ((13, 3), Tile Grass Nothing [Walk, Fly])
    , ((14, 3), Tile Grass Nothing [Walk, Fly])
    , ((15, 3), Tile Grass Nothing [Walk, Fly])
    , ((16, 3), Tile Grass Nothing [Walk, Fly])
    , ((17, 3), Tile Water Nothing [Fly, Swim])
    , ((18, 3), Tile Water Nothing [Fly, Swim])
    , ((19, 3), Tile Water Nothing [Fly, Swim])
    , ((20, 3), Tile Water Nothing [Fly, Swim])
    , ((21, 3), Tile Grass Nothing [Walk, Fly])
    , ((22, 3), Tile Grass Nothing [Walk, Fly])
    , ((23, 3), Tile Grass Nothing [Walk, Fly])
    , ((24, 3), Tile Grass Nothing [Walk, Fly])
    , ((25, 3), Tile Grass Nothing [])
    , ((0, 4), Tile Grass Nothing [])
    , ((1, 4), Tile Grass Nothing [Walk, Fly])
    , ((2, 4), Tile Grass Nothing [Walk, Fly])
    , ((3, 4), Tile Grass Nothing [Walk, Fly])
    , ((4, 4), Tile Grass Nothing [Walk, Fly])
    , ((5, 4), Tile Grass Nothing [Walk, Fly])
    , ((6, 4), Tile Grass Nothing [Walk, Fly])
    , ((7, 4), Tile Grass Nothing [Walk, Fly])
    , ((8, 4), Tile Grass Nothing [Walk, Fly])
    , ((9, 4), Tile Grass Nothing [Walk, Fly])
    , ((10, 4), Tile Grass Nothing [Walk, Fly])
    , ((11, 4), Tile Grass Nothing [Walk, Fly])
    , ((12, 4), Tile Grass Nothing [Walk, Fly])
    , ((13, 4), Tile Grass Nothing [Walk, Fly])
    , ((14, 4), Tile Grass Nothing [Walk, Fly])
    , ((15, 4), Tile Grass Nothing [Walk, Fly])
    , ((16, 4), Tile Water Nothing [Fly, Swim])
    , ((17, 4), Tile Water Nothing [Fly, Swim])
    , ((18, 4), Tile Rocky Nothing [])
    , ((19, 4), Tile Water Nothing [Fly, Swim])
    , ((20, 4), Tile Water Nothing [Fly, Swim])
    , ((21, 4), Tile Grass Nothing [Walk, Fly])
    , ((22, 4), Tile Grass Nothing [Walk, Fly])
    , ((23, 4), Tile Grass Nothing [Walk, Fly])
    , ((24, 4), Tile Grass Nothing [Walk, Fly])
    , ((25, 4), Tile Grass Nothing [])
    , ((0, 5), Tile Grass Nothing [])
    , ((1, 5), Tile Grass Nothing [Walk, Fly])
    , ((2, 5), Tile Grass Nothing [Walk, Fly])
    , ((3, 5), Tile Grass Nothing [Walk, Fly])
    , ((4, 5), Tile Grass Nothing [Walk, Fly])
    , ((5, 5), Tile Grass Nothing [Walk, Fly])
    , ((6, 5), Tile Grass Nothing [Walk, Fly])
    , ((7, 5), Tile Grass Nothing [Walk, Fly])
    , ((8, 5), Tile Grass Nothing [Walk, Fly])
    , ((9, 5), Tile Grass Nothing [Walk, Fly])
    , ((10, 5), Tile Grass Nothing [Walk, Fly])
    , ((11, 5), Tile Grass Nothing [Walk, Fly])
    , ((12, 5), Tile Grass Nothing [Walk, Fly])
    , ((13, 5), Tile Grass Nothing [Walk, Fly])
    , ((14, 5), Tile Grass Nothing [Walk, Fly])
    , ((15, 5), Tile Grass Nothing [Walk, Fly])
    , ((16, 5), Tile Water Nothing [Fly, Swim])
    , ((17, 5), Tile Water Nothing [Fly, Swim])
    , ((18, 5), Tile Water Nothing [Fly, Swim])
    , ((19, 5), Tile Water Nothing [Fly, Swim])
    , ((20, 5), Tile Grass Nothing [Walk, Fly])
    , ((21, 5), Tile Grass Nothing [Walk, Fly])
    , ((22, 5), Tile Grass Nothing [Walk, Fly])
    , ((23, 5), Tile Grass Nothing [Walk, Fly])
    , ((24, 5), Tile Grass Nothing [Walk, Fly])
    , ((25, 5), Tile Grass Nothing [])
    , ((0, 6), Tile Grass Nothing [])
    , ((1, 6), Tile Grass Nothing [Walk, Fly])
    , ((2, 6), Tile Grass Nothing [Walk, Fly])
    , ((3, 6), Tile Grass Nothing [Walk, Fly])
    , ((4, 6), Tile Grass Nothing [Walk, Fly])
    , ((5, 6), Tile Grass Nothing [Walk, Fly])
    , ((6, 6), Tile Grass Nothing [Walk, Fly])
    , ((7, 6), Tile Grass Nothing [Walk, Fly])
    , ((8, 6), Tile Grass Nothing [Walk, Fly])
    , ((9, 6), Tile Grass Nothing [Walk, Fly])
    , ((10, 6), Tile Grass Nothing [Walk, Fly])
    , ((11, 6), Tile Grass Nothing [Walk, Fly])
    , ((12, 6), Tile Grass Nothing [Walk, Fly])
    , ((13, 6), Tile Grass Nothing [Walk, Fly])
    , ((14, 6), Tile Grass Nothing [Walk, Fly])
    , ((15, 6), Tile Grass Nothing [Walk, Fly])
    , ((16, 6), Tile Grass Nothing [Walk, Fly])
    , ((17, 6), Tile Water Nothing [Fly, Swim])
    , ((18, 6), Tile Water Nothing [Fly, Swim])
    , ((19, 6), Tile Grass Nothing [Walk, Fly])
    , ((20, 6), Tile Grass Nothing [Walk, Fly])
    , ((21, 6), Tile Grass Nothing [Walk, Fly])
    , ((22, 6), Tile Grass Nothing [Walk, Fly])
    , ((23, 6), Tile Grass Nothing [Walk, Fly])
    , ((24, 6), Tile Grass Nothing [Walk, Fly])
    , ((25, 6), Tile Grass Nothing [])
    , ((0, 7), Tile Grass Nothing [])
    , ((1, 7), Tile Grass Nothing [Walk, Fly])
    , ((2, 7), Tile Grass Nothing [Walk, Fly])
    , ((3, 7), Tile Grass Nothing [Walk, Fly])
    , ((4, 7), Tile Grass Nothing [Walk, Fly])
    , ((5, 7), Tile Grass Nothing [Walk, Fly])
    , ((6, 7), Tile Grass Nothing [Walk, Fly])
    , ((7, 7), Tile Grass Nothing [Walk, Fly])
    , ((8, 7), Tile Grass Nothing [Walk, Fly])
    , ((9, 7), Tile Grass Nothing [Walk, Fly])
    , ((10, 7), Tile Grass Nothing [Walk, Fly])
    , ((11, 7), Tile Grass Nothing [Walk, Fly])
    , ((12, 7), Tile Grass Nothing [Walk, Fly])
    , ((13, 7), Tile Grass Nothing [Walk, Fly])
    , ((14, 7), Tile Grass Nothing [Walk, Fly])
    , ((15, 7), Tile Grass Nothing [Walk, Fly])
    , ((16, 7), Tile Grass Nothing [Walk, Fly])
    , ((17, 7), Tile Grass Nothing [Walk, Fly])
    , ((18, 7), Tile Grass Nothing [Walk, Fly])
    , ((19, 7), Tile Grass Nothing [Walk, Fly])
    , ((20, 7), Tile Grass Nothing [Walk, Fly])
    , ((21, 7), Tile Grass Nothing [Walk, Fly])
    , ((22, 7), Tile Grass Nothing [Walk, Fly])
    , ((23, 7), Tile Grass Nothing [Walk, Fly])
    , ((24, 7), Tile Grass Nothing [Walk, Fly])
    , ((25, 7), Tile Grass Nothing [])
    , ((0, 8), Tile Grass Nothing [])
    , ((1, 8), Tile Grass Nothing [Walk, Fly])
    , ((2, 8), Tile Grass Nothing [Walk, Fly])
    , ((3, 8), Tile Grass Nothing [Walk, Fly])
    , ((4, 8), Tile Grass Nothing [Walk, Fly])
    , ((5, 8), Tile Grass Nothing [Walk, Fly])
    , ((6, 8), Tile Grass Nothing [Walk, Fly])
    , ((7, 8), Tile Grass Nothing [Walk, Fly])
    , ((8, 8), Tile Grass Nothing [Walk, Fly])
    , ((9, 8), Tile Grass Nothing [Walk, Fly])
    , ((10, 8), Tile Grass Nothing [Walk, Fly])
    , ((11, 8), Tile Grass Nothing [Walk, Fly])
    , ((12, 8), Tile Grass Nothing [Walk, Fly])
    , ((13, 8), Tile Grass Nothing [Walk, Fly])
    , ((14, 8), Tile Grass Nothing [Walk, Fly])
    , ((15, 8), Tile Grass Nothing [Walk, Fly])
    , ((16, 8), Tile Grass Nothing [Walk, Fly])
    , ((17, 8), Tile Grass Nothing [Walk, Fly])
    , ((18, 8), Tile Grass Nothing [Walk, Fly])
    , ((19, 8), Tile Grass Nothing [Walk, Fly])
    , ((20, 8), Tile Grass Nothing [Walk, Fly])
    , ((21, 8), Tile Grass Nothing [Walk, Fly])
    , ((22, 8), Tile Grass Nothing [Walk, Fly])
    , ((23, 8), Tile Grass Nothing [Walk, Fly])
    , ((24, 8), Tile Grass Nothing [Walk, Fly])
    , ((25, 8), Tile Grass Nothing [])
    , ((0, 9), Tile Grass Nothing [])
    , ((1, 9), Tile Grass Nothing [Walk, Fly])
    , ((2, 9), Tile Grass Nothing [Walk, Fly])
    , ((3, 9), Tile Grass Nothing [Walk, Fly])
    , ((4, 9), Tile Grass Nothing [Walk, Fly])
    , ((5, 9), Tile Grass Nothing [Walk, Fly])
    , ((6, 9), Tile Grass Nothing [Walk, Fly])
    , ((7, 9), Tile Grass Nothing [Walk, Fly])
    , ((8, 9), Tile Grass Nothing [Walk, Fly])
    , ((9, 9), Tile Grass Nothing [Walk, Fly])
    , ((10, 9), Tile Grass Nothing [Walk, Fly])
    , ((11, 9), Tile Grass Nothing [Walk, Fly])
    , ((12, 9), Tile Grass Nothing [Walk, Fly])
    , ((13, 9), Tile Grass Nothing [Walk, Fly])
    , ((14, 9), Tile Grass Nothing [Walk, Fly])
    , ((15, 9), Tile Grass Nothing [Walk, Fly])
    , ((16, 9), Tile Grass Nothing [Walk, Fly])
    , ((17, 9), Tile Grass Nothing [Walk, Fly])
    , ((18, 9), Tile Grass Nothing [Walk, Fly])
    , ((19, 9), Tile Grass Nothing [Walk, Fly])
    , ((20, 9), Tile Grass Nothing [Walk, Fly])
    , ((21, 9), Tile Grass Nothing [Walk, Fly])
    , ((22, 9), Tile Grass Nothing [Walk, Fly])
    , ((23, 9), Tile Grass Nothing [Walk, Fly])
    , ((24, 9), Tile Grass Nothing [Walk, Fly])
    , ((25, 9), Tile Grass Nothing [])
    , ((0, 10), Tile Grass Nothing [])
    , ((1, 10), Tile Grass Nothing [Walk, Fly])
    , ((2, 10), Tile Grass Nothing [Walk, Fly])
    , ((3, 10), Tile Grass Nothing [Walk, Fly])
    , ((4, 10), Tile Grass Nothing [Walk, Fly])
    , ((5, 10), Tile Grass Nothing [Walk, Fly])
    , ((6, 10), Tile Rocky Nothing [])
    , ((7, 10), Tile Grass Nothing [Walk, Fly])
    , ((8, 10), Tile Grass Nothing [Walk, Fly])
    , ((9, 10), Tile Grass Nothing [Walk, Fly])
    , ((10, 10), Tile Grass Nothing [Walk, Fly])
    , ((11, 10), Tile Grass Nothing [Walk, Fly])
    , ((12, 10), Tile Grass Nothing [Walk, Fly])
    , ((13, 10), Tile Grass Nothing [Walk, Fly])
    , ((14, 10), Tile Grass Nothing [Walk, Fly])
    , ((15, 10), Tile Grass Nothing [Walk, Fly])
    , ((16, 10), Tile Grass Nothing [Walk, Fly])
    , ((17, 10), Tile Grass Nothing [Walk, Fly])
    , ((18, 10), Tile Grass Nothing [Walk, Fly])
    , ((19, 10), Tile Grass Nothing [Walk, Fly])
    , ((20, 10), Tile Grass Nothing [Walk, Fly])
    , ((21, 10), Tile Grass Nothing [Walk, Fly])
    , ((22, 10), Tile Grass Nothing [Walk, Fly])
    , ((23, 10), Tile Grass Nothing [Walk, Fly])
    , ((24, 10), Tile Grass Nothing [Walk, Fly])
    , ((25, 10), Tile Grass Nothing [])
    , ((0, 11), Tile Grass Nothing [])
    , ((1, 11), Tile Grass Nothing [Walk, Fly])
    , ((2, 11), Tile Grass Nothing [Walk, Fly])
    , ((3, 11), Tile Grass Nothing [Walk, Fly])
    , ((4, 11), Tile Grass Nothing [Walk, Fly])
    , ((5, 11), Tile Grass Nothing [Walk, Fly])
    , ((6, 11), Tile Rocky Nothing [])
    , ((7, 11), Tile Rocky Nothing [])
    , ((8, 11), Tile Grass Nothing [Walk, Fly])
    , ((9, 11), Tile Grass Nothing [Walk, Fly])
    , ((10, 11), Tile Grass Nothing [Walk, Fly])
    , ((11, 11), Tile Grass Nothing [Walk, Fly])
    , ((12, 11), Tile Grass Nothing [Walk, Fly])
    , ((13, 11), Tile Grass Nothing [Walk, Fly])
    , ((14, 11), Tile Grass Nothing [Walk, Fly])
    , ((15, 11), Tile Grass Nothing [Walk, Fly])
    , ((16, 11), Tile Water Nothing [Fly, Swim])
    , ((17, 11), Tile Water Nothing [Fly, Swim])
    , ((18, 11), Tile Rocky Nothing [])
    , ((19, 11), Tile Rocky Nothing [])
    , ((20, 11), Tile Grass Nothing [Walk, Fly])
    , ((21, 11), Tile Grass Nothing [Walk, Fly])
    , ((22, 11), Tile Grass Nothing [Walk, Fly])
    , ((23, 11), Tile Grass Nothing [Walk, Fly])
    , ((24, 11), Tile Grass Nothing [Walk, Fly])
    , ((25, 11), Tile Grass Nothing [])
    , ((0, 12), Tile Grass Nothing [])
    , ((1, 12), Tile Grass Nothing [Walk, Fly])
    , ((2, 12), Tile Grass Nothing [Walk, Fly])
    , ((3, 12), Tile Grass Nothing [Walk, Fly])
    , ((4, 12), Tile Grass Nothing [Walk, Fly])
    , ((5, 12), Tile Grass Nothing [Walk, Fly])
    , ((6, 12), Tile Rocky Nothing [])
    , ((7, 12), Tile Rocky Nothing [])
    , ((8, 12), Tile Rocky Nothing [])
    , ((9, 12), Tile Water Nothing [Fly, Swim])
    , ((10, 12), Tile Water Nothing [Fly, Swim])
    , ((11, 12), Tile Water Nothing [Fly, Swim])
    , ((12, 12), Tile Water Nothing [Fly, Swim])
    , ((13, 12), Tile Water Nothing [Fly, Swim])
    , ((14, 12), Tile Grass Nothing [Walk, Fly])
    , ((15, 12), Tile Water Nothing [Fly, Swim])
    , ((16, 12), Tile Water Nothing [Fly, Swim])
    , ((17, 12), Tile Rocky Nothing [])
    , ((18, 12), Tile Rocky Nothing [])
    , ((19, 12), Tile Rocky Nothing [])
    , ((20, 12), Tile Grass Nothing [Walk, Fly])
    , ((21, 12), Tile Grass Nothing [Walk, Fly])
    , ((22, 12), Tile Grass Nothing [Walk, Fly])
    , ((23, 12), Tile Grass Nothing [Walk, Fly])
    , ((24, 12), Tile Grass Nothing [Walk, Fly])
    , ((25, 12), Tile Grass Nothing [])
    , ((0, 13), Tile Grass Nothing [])
    , ((1, 13), Tile Grass Nothing [Walk, Fly])
    , ((2, 13), Tile Grass Nothing [Walk, Fly])
    , ((3, 13), Tile Grass Nothing [Walk, Fly])
    , ((4, 13), Tile Grass Nothing [Walk, Fly])
    , ((5, 13), Tile Grass Nothing [Walk, Fly])
    , ((6, 13), Tile Rocky Nothing [])
    , ((7, 13), Tile Rocky Nothing [])
    , ((8, 13), Tile Rocky Nothing [])
    , ((9, 13), Tile Rocky Nothing [])
    , ((10, 13), Tile Water Nothing [Fly, Swim])
    , ((11, 13), Tile Water Nothing [Fly, Swim])
    , ((12, 13), Tile Water Nothing [Fly, Swim])
    , ((13, 13), Tile Water Nothing [Fly, Swim])
    , ((14, 13), Tile Water Nothing [Fly, Swim])
    , ((15, 13), Tile Water Nothing [Fly, Swim])
    , ((16, 13), Tile Water Nothing [Fly, Swim])
    , ((17, 13), Tile Rocky Nothing [])
    , ((18, 13), Tile Rocky Nothing [])
    , ((19, 13), Tile Rocky Nothing [])
    , ((20, 13), Tile Grass Nothing [Walk, Fly])
    , ((21, 13), Tile Grass Nothing [Walk, Fly])
    , ((22, 13), Tile Grass Nothing [Walk, Fly])
    , ((23, 13), Tile Grass Nothing [Walk, Fly])
    , ((24, 13), Tile Grass Nothing [Walk, Fly])
    , ((25, 13), Tile Grass Nothing [])
    , ((0, 14), Tile Grass Nothing [])
    , ((1, 14), Tile Grass Nothing [Walk, Fly])
    , ((2, 14), Tile Grass Nothing [Walk, Fly])
    , ((3, 14), Tile Grass Nothing [Walk, Fly])
    , ((4, 14), Tile Grass Nothing [Walk, Fly])
    , ((5, 14), Tile Grass Nothing [Walk, Fly])
    , ((6, 14), Tile Grass Nothing [Walk, Fly])
    , ((7, 14), Tile Rocky Nothing [])
    , ((8, 14), Tile Rocky Nothing [])
    , ((9, 14), Tile Rocky Nothing [])
    , ((10, 14), Tile Rocky Nothing [])
    , ((11, 14), Tile Rocky Nothing [])
    , ((12, 14), Tile Rocky Nothing [])
    , ((13, 14), Tile Rocky Nothing [])
    , ((14, 14), Tile Rocky Nothing [])
    , ((15, 14), Tile Rocky Nothing [])
    , ((16, 14), Tile Rocky Nothing [])
    , ((17, 14), Tile Rocky Nothing [])
    , ((18, 14), Tile Rocky Nothing [])
    , ((19, 14), Tile Grass Nothing [Walk, Fly])
    , ((20, 14), Tile Grass Nothing [Walk, Fly])
    , ((21, 14), Tile Grass Nothing [Walk, Fly])
    , ((22, 14), Tile Grass Nothing [Walk, Fly])
    , ((23, 14), Tile Grass Nothing [Walk, Fly])
    , ((24, 14), Tile Grass Nothing [Walk, Fly])
    , ((25, 14), Tile Grass Nothing [])
    , ((0, 15), Tile Grass Nothing [])
    , ((1, 15), Tile Grass Nothing [Walk, Fly])
    , ((2, 15), Tile Grass Nothing [Walk, Fly])
    , ((3, 15), Tile Grass Nothing [Walk, Fly])
    , ((4, 15), Tile Grass Nothing [Walk, Fly])
    , ((5, 15), Tile Grass Nothing [Walk, Fly])
    , ((6, 15), Tile Grass Nothing [Walk, Fly])
    , ((7, 15), Tile Grass Nothing [Walk, Fly])
    , ((8, 15), Tile Rocky Nothing [])
    , ((9, 15), Tile Rocky Nothing [])
    , ((10, 15), Tile Rocky Nothing [])
    , ((11, 15), Tile Snow Nothing [Walk, Fly])
    , ((12, 15), Tile Snow Nothing [Walk, Fly])
    , ((13, 15), Tile Snow Nothing [Walk, Fly])
    , ((14, 15), Tile Rocky Nothing [])
    , ((15, 15), Tile Rocky Nothing [])
    , ((16, 15), Tile Rocky Nothing [])
    , ((17, 15), Tile Rocky Nothing [])
    , ((18, 15), Tile Rocky Nothing [])
    , ((19, 15), Tile Grass Nothing [Walk, Fly])
    , ((20, 15), Tile Grass Nothing [Walk, Fly])
    , ((21, 15), Tile Grass Nothing [Walk, Fly])
    , ((22, 15), Tile Grass Nothing [Walk, Fly])
    , ((23, 15), Tile Grass Nothing [Walk, Fly])
    , ((24, 15), Tile Grass Nothing [Walk, Fly])
    , ((25, 15), Tile Grass Nothing [])
    , ((0, 16), Tile Grass Nothing [])
    , ((1, 16), Tile Grass Nothing [Walk, Fly])
    , ((2, 16), Tile Grass Nothing [Walk, Fly])
    , ((3, 16), Tile Grass Nothing [Walk, Fly])
    , ((4, 16), Tile Grass Nothing [Walk, Fly])
    , ((5, 16), Tile Grass Nothing [Walk, Fly])
    , ((6, 16), Tile Grass Nothing [Walk, Fly])
    , ((7, 16), Tile Grass Nothing [Walk, Fly])
    , ((8, 16), Tile Grass Nothing [Walk, Fly])
    , ((9, 16), Tile Rocky Nothing [])
    , ((10, 16), Tile Rocky Nothing [])
    , ((11, 16), Tile Snow Nothing [Walk, Fly])
    , ((12, 16), Tile Snow Nothing [Walk, Fly])
    , ((13, 16), Tile Snow Nothing [Walk, Fly])
    , ((14, 16), Tile Snow Nothing [Walk, Fly])
    , ((15, 16), Tile Rocky Nothing [])
    , ((16, 16), Tile Rocky Nothing [])
    , ((17, 16), Tile Grass Nothing [Walk, Fly])
    , ((18, 16), Tile Grass Nothing [Walk, Fly])
    , ((19, 16), Tile Grass Nothing [Walk, Fly])
    , ((20, 16), Tile Grass Nothing [Walk, Fly])
    , ((21, 16), Tile Grass Nothing [Walk, Fly])
    , ((22, 16), Tile Grass Nothing [Walk, Fly])
    , ((23, 16), Tile Grass Nothing [Walk, Fly])
    , ((24, 16), Tile Grass Nothing [Walk, Fly])
    , ((25, 16), Tile Grass Nothing [])
    , ((0, 17), Tile Grass Nothing [])
    , ((1, 17), Tile Grass Nothing [Walk, Fly])
    , ((2, 17), Tile Grass Nothing [Walk, Fly])
    , ((3, 17), Tile Grass Nothing [Walk, Fly])
    , ((4, 17), Tile Grass Nothing [Walk, Fly])
    , ((5, 17), Tile Grass Nothing [Walk, Fly])
    , ((6, 17), Tile Grass Nothing [Walk, Fly])
    , ((7, 17), Tile Grass Nothing [Walk, Fly])
    , ((8, 17), Tile Grass Nothing [Walk, Fly])
    , ((9, 17), Tile Grass Nothing [Walk, Fly])
    , ((10, 17), Tile Rocky Nothing [])
    , ((11, 17), Tile Rocky Nothing [])
    , ((12, 17), Tile Rocky Nothing [])
    , ((13, 17), Tile Rocky Nothing [])
    , ((14, 17), Tile Rocky Nothing [])
    , ((15, 17), Tile Rocky Nothing [])
    , ((16, 17), Tile Grass Nothing [Walk, Fly])
    , ((17, 17), Tile Grass Nothing [Walk, Fly])
    , ((18, 17), Tile Grass Nothing [Walk, Fly])
    , ((19, 17), Tile Grass Nothing [Walk, Fly])
    , ((20, 17), Tile Grass Nothing [Walk, Fly])
    , ((21, 17), Tile Grass Nothing [Walk, Fly])
    , ((22, 17), Tile Grass Nothing [Walk, Fly])
    , ((23, 17), Tile Grass Nothing [Walk, Fly])
    , ((24, 17), Tile Grass Nothing [Walk, Fly])
    , ((25, 17), Tile Grass Nothing [])
    , ((0, 18), Tile Grass Nothing [])
    , ((1, 18), Tile Grass Nothing [Walk, Fly])
    , ((2, 18), Tile Grass Nothing [Walk, Fly])
    , ((3, 18), Tile Grass Nothing [Walk, Fly])
    , ((4, 18), Tile Grass Nothing [Walk, Fly])
    , ((5, 18), Tile Grass Nothing [Walk, Fly])
    , ((6, 18), Tile Grass Nothing [Walk, Fly])
    , ((7, 18), Tile Grass Nothing [Walk, Fly])
    , ((8, 18), Tile Grass Nothing [Walk, Fly])
    , ((9, 18), Tile Grass Nothing [Walk, Fly])
    , ((10, 18), Tile Grass Nothing [Walk, Fly])
    , ((11, 18), Tile Grass Nothing [Walk, Fly])
    , ((12, 18), Tile Grass Nothing [Walk, Fly])
    , ((13, 18), Tile Grass Nothing [Walk, Fly])
    , ((14, 18), Tile Grass Nothing [Walk, Fly])
    , ((15, 18), Tile Grass Nothing [Walk, Fly])
    , ((16, 18), Tile Grass Nothing [Walk, Fly])
    , ((17, 18), Tile Grass Nothing [Walk, Fly])
    , ((18, 18), Tile Grass Nothing [Walk, Fly])
    , ((19, 18), Tile Grass Nothing [Walk, Fly])
    , ((20, 18), Tile Grass Nothing [Walk, Fly])
    , ((21, 18), Tile Grass Nothing [Walk, Fly])
    , ((22, 18), Tile Grass Nothing [Walk, Fly])
    , ((23, 18), Tile Grass Nothing [Walk, Fly])
    , ((24, 18), Tile Grass Nothing [Walk, Fly])
    , ((25, 18), Tile Grass Nothing [])
    , ((0, 19), Tile Grass Nothing [])
    , ((1, 19), Tile Grass Nothing [Walk, Fly])
    , ((2, 19), Tile Grass Nothing [Walk, Fly])
    , ((3, 19), Tile Grass Nothing [Walk, Fly])
    , ((4, 19), Tile Grass Nothing [Walk, Fly])
    , ((5, 19), Tile Grass Nothing [Walk, Fly])
    , ((6, 19), Tile Grass Nothing [Walk, Fly])
    , ((7, 19), Tile Grass Nothing [Walk, Fly])
    , ((8, 19), Tile Grass Nothing [Walk, Fly])
    , ((9, 19), Tile Grass Nothing [Walk, Fly])
    , ((10, 19), Tile Grass Nothing [Walk, Fly])
    , ((11, 19), Tile Grass Nothing [Walk, Fly])
    , ((12, 19), Tile Grass Nothing [Walk, Fly])
    , ((13, 19), Tile Grass Nothing [Walk, Fly])
    , ((14, 19), Tile Grass Nothing [Walk, Fly])
    , ((15, 19), Tile Grass Nothing [Walk, Fly])
    , ((16, 19), Tile Grass Nothing [Walk, Fly])
    , ((17, 19), Tile Grass Nothing [Walk, Fly])
    , ((18, 19), Tile Grass Nothing [Walk, Fly])
    , ((19, 19), Tile Grass Nothing [Walk, Fly])
    , ((20, 19), Tile Grass Nothing [Walk, Fly])
    , ((21, 19), Tile Grass Nothing [Walk, Fly])
    , ((22, 19), Tile Grass Nothing [Walk, Fly])
    , ((23, 19), Tile Grass Nothing [Walk, Fly])
    , ((24, 19), Tile Grass Nothing [Walk, Fly])
    , ((25, 19), Tile Grass Nothing [])
    , ((0, 20), Tile Grass Nothing [])
    , ((1, 20), Tile Grass Nothing [])
    , ((2, 20), Tile Grass Nothing [])
    , ((3, 20), Tile Grass Nothing [])
    , ((4, 20), Tile Grass Nothing [])
    , ((5, 20), Tile Grass Nothing [])
    , ((6, 20), Tile Grass Nothing [])
    , ((7, 20), Tile Grass Nothing [])
    , ((8, 20), Tile Grass Nothing [])
    , ((9, 20), Tile Grass Nothing [])
    , ((10, 20), Tile Grass Nothing [])
    , ((11, 20), Tile Grass Nothing [])
    , ((12, 20), Tile Grass Nothing [])
    , ((13, 20), Tile Grass Nothing [])
    , ((14, 20), Tile Grass Nothing [])
    , ((15, 20), Tile Grass Nothing [])
    , ((16, 20), Tile Grass Nothing [])
    , ((17, 20), Tile Grass Nothing [])
    , ((18, 20), Tile Grass Nothing [])
    , ((19, 20), Tile Grass Nothing [])
    , ((20, 20), Tile Grass Nothing [])
    , ((21, 20), Tile Grass Nothing [])
    , ((22, 20), Tile Grass Nothing [])
    , ((23, 20), Tile Grass Nothing [])
    , ((24, 20), Tile Grass Nothing [])
    , ((25, 20), Tile Grass Nothing [])
    ]
  }
